WIP: Can this type be constructed just with the NodeAssembler / MapAssembler
Question, can we construct Alpha without explicitly invoking Beta's prototype? Or does some logic need to exist that understands "delta:1,2" can be used to construct a Beta which can be passed to Alpha's constructor.

---------------------------

--- FAIL: TestSchema (0.00s)
    --- FAIL: TestSchema/StructAlphaDelta (0.00s)
panic: func called on wrong kind: "AssignString" called on a Beta node (kind: map), but only makes sense on string [recovered]
	panic: func called on wrong kind: "AssignString" called on a Beta node (kind: map), but only makes sense on string

goroutine 118 [running]:
testing.tRunner.func1.2({0x1394c60, 0xc00023dca0})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x1394c60, 0xc00023dca0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/ipld/go-ipld-prime/fluent.(*nodeAssembler).AssignString(0x10?, {0x13e0464?, 0xc0001d1c01?})
	/Users/dlong/dev/go-code/go-ipld-prime/fluent/fluentBuilder.go:133 +0x65
github.com/ipld/go-ipld-prime/node/tests.SchemaAlphaDelta.func1.1({0x1460a18?, 0xc00023dc70?})
	/Users/dlong/dev/go-code/go-ipld-prime/node/tests/schemaStructReprStringjoin.go:214 +0x48
github.com/ipld/go-ipld-prime/fluent.(*nodeAssembler).CreateMap(0x10?, 0x138d980?, 0x13fb160)
	/Users/dlong/dev/go-code/go-ipld-prime/fluent/fluentBuilder.go:95 +0x87
github.com/ipld/go-ipld-prime/fluent.MustBuildMap.func1({0x1461ef0?, 0xc00023dc60?})
	/Users/dlong/dev/go-code/go-ipld-prime/fluent/fluentBuilder.go:31 +0x32
github.com/ipld/go-ipld-prime/fluent.MustBuild({0x145d460?, 0xc000251b90?}, 0xc0001d1cf0)
	/Users/dlong/dev/go-code/go-ipld-prime/fluent/fluentBuilder.go:27 +0x9b
github.com/ipld/go-ipld-prime/fluent.MustBuildMap({0x145d460?, 0xc000251b90?}, 0x138d980?, 0xc000241001?)
	/Users/dlong/dev/go-code/go-ipld-prime/fluent/fluentBuilder.go:31 +0x4d
github.com/ipld/go-ipld-prime/node/tests.SchemaAlphaDelta.func1({0xc000251b90?, 0x5?})
	/Users/dlong/dev/go-code/go-ipld-prime/node/tests/schemaStructReprStringjoin.go:213 +0x2d
github.com/ipld/go-ipld-prime/fluent.MustBuild({0x145d460?, 0xc000251b90?}, 0xc0001d1e10)
	/Users/dlong/dev/go-code/go-ipld-prime/fluent/fluentBuilder.go:27 +0x9b
github.com/ipld/go-ipld-prime/node/tests.SchemaAlphaDelta(0x13e3d23?, {0x145e7b0, 0xc000246e40})
	/Users/dlong/dev/go-code/go-ipld-prime/node/tests/schemaStructReprStringjoin.go:212 +0x5eb
github.com/ipld/go-ipld-prime/node/tests.SchemaTestAll.func1(0xc00036c4e0)
	/Users/dlong/dev/go-code/go-ipld-prime/node/tests/schema.go:51 +0x169
testing.tRunner(0xc00036c4e0, 0xc0003326c0)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f